// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage/Blended.tsx": () => import("../components/mockups/homepage/Blended.tsx"),
  "./components/mockups/homepage/FeatureLed.tsx": () => import("../components/mockups/homepage/FeatureLed.tsx"),
  "./components/mockups/homepage/ValueLed.tsx": () => import("../components/mockups/homepage/ValueLed.tsx")
};
